# Generated by Django 4.2.3 on 2023-07-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
    ]
